### ISSUE TITLE
Handle Multiple CPUs

### ISSUE THREAD

**Issue by ysdragon** [ysdragon/SysInfo#1]
Add support to handle multiple CPUs for both Linux and Windows.

**Comment by mayouni** [comment]
Hello DraGonN,

It seems like the messages are posted directly from GitHub. But we can't
understand what they zre about here...

Can you give us some context please.

All the best,
Mansour

**Comment by ysdragon** [comment]
Hello Mansour,

I'm not entirely sure, but it may be because I used `git commit --amend` to edit the commit.

Best regards,
Youssef

**Comment by mayouni** [comment]
Ok, thanks for the clarification.
Best,
Mansour
